### PR TITLE
Updates From CM Repo And Revert The Conflicts

### PR DESCRIPTION
**Pull request by devam03**

### CODE REVIEW

**Comment by akhilnarang** [comment]
Too many conflicts
First just revert, later push updates from cm

**Comment by KunalKene1797** [comment]
Make these 2 commits and push then resolve the remaining conflicts!
Settings: re-index search after setting new lockscreen 
Settings: fix search key not opening search 
settings: fix RTL layouts

**Comment by akhilnarang** [comment]
@KunalKene1797  conflicts are because Devam left out one commt in the middle
I'll have to revert ~10 commits, cherry-pick that, then re cherry-pick these
That's why I'm closing this

**Comment by KunalKene1797** [comment]
-___- @devam03, Strike One!

**Comment by akhilnarang** [comment]
@KunalKene1797 @devam03  fixed!

**Pull request closed without merging**
